### PR TITLE
Refactoring to allow for second page, creating Itinerary page

### PR DESCRIPTION
**Pull request by SeokSong**

### CODE REVIEW

**Comment by SeokSong** [comment]
npm install && npm i react-router-dom --save

**Comment by ThomasJu** [comment]
Some nitpick:
1. uncomment the line for loading GoogleApiKey
2. I already made a button for creating an itinerary, but I will fix it after you merge the pull request.

**Review by ThomasJu — COMMENTED** [review]
Some nitpick:

1. uncomment the line for loading GoogleApiKey
2. itinerary page has the same name as HomePage in the function name.
3. I already made a button for creating an itinerary in extraInputOption.tsx, but I will fix it after you merge the pull request.

Overall file structure LGTM. When I pull this request and run it locally with `npm start`, there are compile errors. Could you fix those errors?

**Comment by SeokSong** [comment]
> Some nitpick:
> 
> 1. uncomment the line for loading GoogleApiKey (Done)
> 2. itinerary page has the same name as HomePage in the function name. (changed to PageNavigation)
> 3. I already made a button for creating an itinerary in extraInputOption.tsx, but I will fix it after you merge the pull request.
> 
> Overall file structure LGTM. When I pull this request and run it locally with `npm start`, there are compile errors. Could you fix those errors? (NGL I dont get any compile errors, I'll second a second version that will have more stuff so it will need another review but my current app doesnt error so hopefully the second commit will not error for you too.

**Review by ThomasJu — APPROVED** [review]

**Pull request merged**
